
---
# Beginning of the "Test Playbook" Play
- name:  Test Playbook - demonstrate precedence of Play vs. Task variables
  hosts: all
  vars:
      myvar1: PLAY-hello
      myvar2: PLAY-123
      myvar3: PLAY-True
  
  tasks:
  - name: Show playbook variables
    vars:
      myvar1: hello world
      myvar2: 123
      myvar3: True
    debug:
      msg: "Variable values myvar1={{ myvar1 }}, myvar2={{ myvar2 }}, myvar3={{ myvar3 }}"

  - name: 2 - Show playbook variables
    vars:
      myvar1: HELLO WORLD
      myvar2: 222222
      myvar3: False
    debug:
      msg: "[2] Variable values myvar1={{ myvar1 }}, myvar2={{ myvar2 }}, myvar3={{ myvar3 }}"

  - name: 3 - Show playbook variables
    debug:
      msg: "[3] Variable values myvar1={{ myvar1 }}, myvar2={{ myvar2 }}, myvar3={{ myvar3 }}"
