
---

# A conditional play:
- hosts: all
  name:  echo-count

  # The list of tasks to perform:
  tasks:
    # Loop:
    - name: looper
      command: echo "VALUE={{ item }}"
      loop: [ 1, 3, 5, 7, 9, 11 ]

    - name: looper-cond
      command: echo "VALUE={{ item }}"
      loop: [ 1, 3, 5, 7, 9, 11 ]
      when: item >= 7
