
---
# Beginning of the "Test Playbook" Play
- name:  Test Playbook - demonstrate Task variables
  hosts: localhost
  connection: local 
  
  tasks:
  - name: Show playbook variables
    vars:
      myvar1: hello world
      myvar2: 123
      myvar3: True
    debug:
      msg: "Variable values myvar1={{ myvar1 }}, myvar2={{ myvar2 }}, myvar3={{ myvar3 }}"

  - name: 2 - Show playbook variables
    vars:
      myvar1: HELLO WORLD
      myvar2: 222222
      myvar3: False
    debug:
      msg: "[2] Variable values myvar1={{ myvar1 }}, myvar2={{ myvar2 }}, myvar3={{ myvar3 }}"
